### ISSUE TITLE
Shini is slow on Cygwin

### ISSUE THREAD

**Issue by thorstenkampe** [wallyhall/shini#8]
My INI file is 136 lines long and it take more than twenty seconds to parse it. This is the newest Cygwin 2.6 on Windows 10 and a SSD drive. Is there anything to improve the speed of `shini`?

**Comment by wallyhall** [comment]
I've made some heavy changes to try and increase the performance, particularly with recent versions of `zsh` and `bash`, has this helped at all?

**Comment by thorstenkampe** [comment]
I tested with a 145 line ini file and the provided modified `example.sh`

- Bash: shini 1.0 takes 44.8 seconds to parse the file and the current master takes 0.86 seconds
- Zsh: shini 1.0 takes 41.7 seconds to parse the file and the current master takes 0.7 seconds

I also noticed a difference in parsing: multiline entries throw an error (`shini: Unable to parse line 4:`) in 1.0 while they're ignored in the current master.

```
test_stdout       = <div class="paragraph">
                     <p>Hello, World!</p>
                     </div>
```

**Comment by wallyhall** [comment]
(Apologies btw for not getting to your issue sooner - I changed jobs last year and it's been insanely busy until a few weeks ago, and I completely overlooked the issue you raised.)

That's definitely the kind of performance improvement I was hoping for...!

Thanks for catching the issue about multi-lines, I obviously wasn't testing for that scenario.  I'll update the build tests this weekend to include that, and I'll look for a fix.  (I've switched from calling `grep` to builtin regex tests - I'm certain that'll contain the root cause.)

**Comment by thorstenkampe** [comment]
For the record and comparison: I switched to `crudini` (written in Python) some time ago. Crudini cannot parse the whole file at once (only section-wise). The time needed to do that is 3.5 seconds (compared to 0.7 for `shini`)

**Comment by wallyhall** [comment]
I'm surprised it's so much slower - I've not seen that lib before, but I'm curious now.

Originally this only stated as a quick hack for something my former employer needed, processing `my.cnf` files across a cluster of servers.  The files were tiny, so performance was never a concern (in the first instance).
